---
title: "Covid and crafts - analysis"
author: "Sille Hasselbalch Markussen"
date: "12/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(tidyverse, scales)
```

```{r}
knit_pat <- read_csv("/Users/Sillemarkussen/Desktop/Cultural Data Science/au679472_markussen_sille/Final_project/clean_data/ravelry_knit_data_clean.csv")
lockdown <- read_csv("/Users/Sillemarkussen/Desktop/Cultural Data Science/au679472_markussen_sille/Final_project/clean_data/lockdown_data_clean.csv")
```

```{r plotting}
publishCountry <- ggplot(knit_pat, aes(published_year_long))+
  geom_bar(colour = "#a3c2c2", fill="#669999")+
  facet_wrap(~as.factor(country))+
  theme_bw()+
  labs(x = "Year of Publishment", y = "Number of published patterns")+  
  theme(axis.text=element_text(size=12)) +
  theme(axis.title=element_text(size=14)) +
  theme(strip.text=element_text(size=14))

ggsave("publishCountry.png", plot = publishCountry, width = 11, height = 7, dpi = 320)
```

```{r count per month}
knit_pat$published <- as.Date(knit_pat$published, format= "%Y-%m-%d")

pat_pr_month <- knit_pat %>% 
  group_by(published, country) %>% 
  summarise(count_mo=n()) %>% 
  subset(published> "2015-01-01")
```

```{r}
ggplot(pat_pr_month, aes(x = published, y = count_mo, colour = country))+
  geom_line()+
  theme_bw()+
  labs(x = "Date of Publishment", y = "Number of Published Patterns", title = "Amount of Published Patterns Over Time")
```



```{r}
publishTime <- ggplot(pat_pr_month, aes(x = published, y = count_mo, colour = country))+
  geom_line()+
  geom_vline(xintercept = lockdown$Date, size = 0.4, colour = "black")+
  theme_bw()+
  labs(x = "Date of Publishment", y = "Number of Published Patterns", colour = "Country")+
  annotate("text", x = as.Date("2020-08-24", "%Y-%m-%d"), y=16, label = "Lockdown", col="black", size=5, parse=TRUE)+
  annotate("text", x = as.Date("2020-06-30", "%Y-%m-%d"), y=15.35, label = "dates", col="black", size=5, parse=TRUE)+  
  theme(axis.text=element_text(size=12)) +
  theme(axis.title=element_text(size=14))+
  theme(legend.text=element_text(size=14))+
  theme(legend.title=element_text(size=16))
  
ggsave("publishTime.png", plot = publishTime, width = 13, height = 7, dpi = 320)
```


